/**
 * Icon registry — the single file that needs to change when the official
 * Catylast icon library ships. Today this maps Catylast icon names to Lucide
 * components; tomorrow it can map to in-house SVG components without changing
 * the public API or any consumer code.
 *
 * Naming convention: kebab-case names. Add new icons in alphabetical order.
 */
import {
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  Bold,
  Bookmark,
  Box,
  Bug,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardList,
  Clock,
  Code,
  Code2,
  Columns3,
  Copy,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Film,
  Filter,
  Flag,
  Folder,
  Gavel,
  Gift,
  GitBranch,
  GitFork,
  GitMerge,
  GitPullRequest,
  Globe,
  GripVertical,
  Hash,
  Heading,
  Heart,
  HelpCircle,
  Image,
  Info,
  Italic,
  LayoutGrid,
  Lightbulb,
  Link,
  List,
  ListChecks,
  ListOrdered,
  Lock,
  Maximize2,
  Minimize2,
  Minus,
  MoreHorizontal,
  MoreVertical,
  Music,
  PanelLeft,
  Paperclip,
  Pencil,
  Plus,
  Puzzle,
  SquarePlus,
  Quote,
  Redo2,
  Rocket,
  Search,
  Settings,
  Slash,
  Smile,
  Sparkles,
  Star,
  Strikethrough,
  Table,
  Tag,
  Terminal,
  ThumbsUp,
  Trash2,
  Trophy,
  Type,
  Underline,
  Undo2,
  Unlock,
  Upload,
  User,
  UserPlus,
  Users,
  Video,
  X,
  XCircle,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const iconRegistry = {
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "at-sign": AtSign,
  bold: Bold,
  bookmark: Bookmark,
  box: Box,
  bug: Bug,
  calendar: Calendar,
  check: Check,
  "check-circle": CheckCircle,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "clipboard-list": ClipboardList,
  clock: Clock,
  close: X,
  code: Code,
  "code-block": Code2,
  columns: Columns3,
  copy: Copy,
  database: Database,
  download: Download,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  file: File,
  "file-text": FileText,
  film: Film,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  gavel: Gavel,
  gift: Gift,
  "git-branch": GitBranch,
  "git-fork": GitFork,
  "git-merge": GitMerge,
  "git-pull-request": GitPullRequest,
  globe: Globe,
  "grip-vertical": GripVertical,
  hash: Hash,
  heading: Heading,
  heart: Heart,
  "help-circle": HelpCircle,
  image: Image,
  info: Info,
  italic: Italic,
  "layout-grid": LayoutGrid,
  lightbulb: Lightbulb,
  link: Link,
  list: List,
  "list-checks": ListChecks,
  "list-ordered": ListOrdered,
  lock: Lock,
  maximize: Maximize2,
  minimize: Minimize2,
  minus: Minus,
  "more-horizontal": MoreHorizontal,
  "more-vertical": MoreVertical,
  music: Music,
  "panel-left": PanelLeft,
  paperclip: Paperclip,
  pencil: Pencil,
  plus: Plus,
  "plus-square": SquarePlus,
  puzzle: Puzzle,
  quote: Quote,
  redo: Redo2,
  rocket: Rocket,
  search: Search,
  settings: Settings,
  slash: Slash,
  smile: Smile,
  sparkles: Sparkles,
  star: Star,
  strikethrough: Strikethrough,
  table: Table,
  tag: Tag,
  terminal: Terminal,
  "thumbs-up": ThumbsUp,
  trash: Trash2,
  trophy: Trophy,
  type: Type,
  underline: Underline,
  undo: Undo2,
  unlock: Unlock,
  upload: Upload,
  user: User,
  "user-plus": UserPlus,
  users: Users,
  video: Video,
  "x-circle": XCircle,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;

/** Sorted list of every icon name. Useful for icon-picker UIs. */
export const iconNames = Object.keys(iconRegistry).sort() as IconName[];
